### PR TITLE
Refactor + start using Glide

### PR DESCRIPTION
**Pull request by agonzalezro**
This is a big refactor that tries to do a better usage of channel and subrotuines. In fact, the generation speed was improved a lot.

Also, I don't think that adding [GB](https://getgb.io) was a good decission. I am using [glide](https://github.com/Masterminds/glide) now.

Finally, the structure of the templates has changed and I am using the `{% block %}` tag introduced in Go 1.6 (yeah, not backwards compatible, nobody really cares :)

PS: I will be working on this PR because there are still things to do, but your comments would be really appreciated.

### CODE REVIEW

**Comment by ikennaokpala** [comment]
@agonzalezro great piece of work thus far.. a quick glance and nothing immediately pressing.. but it is interesting what you might think of this.. 

```if (* startDaemon) { ```

would it not be plausible to access the main object here as opposed to the pointer.. don't know just a my thought

**Comment by agonzalezro** [comment]
Hi @ikennaokpala! Thanks again for your comment.

`startDaemon` is a kingpin boolean flag (https://github.com/agonzalezro/polo/pull/39/files#diff-3c0900cfd7267956d73086d9ee0faf91R20), I don't actually understand what you are asking.

**Comment by ikennaokpala** [comment]
The idea i am proposeing is for it to be an object with a boolean predicate method.. and where it can be deconstructed back with the parenthesis around (*startDaemon)..

Well just a thought though!! I will rest my case here..

**Comment by ikennaokpala** [comment]
+1

On Mon, May 2, 2016 at 12:28 PM, Alexandre González <
notifications@github.com> wrote:

> Merged #39 <https://github.com/agonzalezro/polo/pull/39>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/agonzalezro/polo/pull/39#event-647476752>
>



-- 
Ikenna

**Pull request merged**
